-- GÜNCEL: Bu fonksiyon + businesses sütunları **supabase-business-opening-hours.sql** içinde yer alır.
-- İşletme profili güncelleme için önce/onunla birlikte o dosyayı SQL Editor’de çalıştırın.
--
-- Opening / closing zamanları `update_panel_business_profile(..., p_opening_time time, p_closing_time time)` ile gelir.
